all: server.out client.out

server.out:
	g++ src/Tracker\ Server\ Skeleton.c -o server.out -w

client.out:
	g++ src/Peer\ Program\ Skeleton.c -o client.out -w

clean:
	rm -rf server.out
	rm -rf client.out
